### ISSUE TITLE
App soft-crashes in course view

### ISSUE THREAD

**Issue by Hialus** [ls1intum/artemis-ios#108] opened 2024-05-29 13:36 UTC
To reproduce:
1. Go to a course
2. Turn the device to the side
3. Switch to another tab
4. Switch back to the exercises tab
5. Turn the device back to the original side
6. App soft crashes and reloads into the course list

Screencast:

https://github.com/ls1intum/artemis-ios/assets/18218285/d4722490-6083-42c1-9320-5d700f4f71ac

**Comment by anian03** [comment] 2024-10-05 13:53
This should be fixed with version 1.3.0, could you please confirm whether the issue is resolved for you?

**Closed** 2024-11-19 20:07 UTC
Labels: bug
